overrides:
  - files: "*.css"

    options:
      parser: css

  - files: "*.scss"

    options:
      parser: scss

  - files: "*.{yaml,yml}"

    options:
      parser: yaml

  - files: "*.md"

    options:
      parser: markdown

  - files: "*.json"

    options:
      parser: json

  - files: "*.html"

    options:
      parser: html
